### ISSUE TITLE
 Set up your Kanban board

### ISSUE THREAD

**Issue by nelsinofrancisco** [nelsinofrancisco/space-travelers#25]
In our team, there are two persons assigned to build the group project.

Link to [gh-project](https://github.com/nelsinofrancisco/space-travelers/projects/1)

**Comment by dasileker** [comment]
### **Hi @nelsinofrancisco,** 

### **Congratulations! 🎉 Project Approved ✅**


![Approved](https://user-images.githubusercontent.com/61562626/135886182-a253c8e2-fc87-4ea5-abb5-2e858e1be8a7.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it 🚀 


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by nelsinofrancisco** [comment]
@dasileker I love The Office memes! Thank you hahaha
